services:
  - type: web
    name: bendix-complete-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET
        generateValue: true
